FROM golang:1.15.6-alpine3.12

RUN apk add --update \
            --no-cache \
            build-base \
            alpine-sdk \
            git

ENV APP_HOME /go-app-template/src
ENV GOPATH /go
ENV GO111MODULE on

WORKDIR $APP_HOME

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

# go mod tidyで消えるので個別にgetする
RUN go get -u github.com/kyoh86/richgo
RUN go get github.com/pilu/fresh
CMD ["fresh"]
# or
#CMD ["go", "run", "/go-app-template/src/main.go"]
