FROM golang:1.15.6-alpine3.12

RUN apk add --update \
            --no-cache \
            build-base \
            alpine-sdk \
            git

ENV APP_HOME /go-app-template/src
ENV GOPATH /go
ENV GO111MODULE on

WORKDIR $APP_HOME

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

#CMD ["go", "run", "/go-app-template/src/main.go"]
# or
RUN go get github.com/pilu/fresh
CMD ["fresh"]
